### ISSUE TITLE
Error playing media due to using section name instead of user library name

### ISSUE THREAD

**Issue by MoRBiD-MaNGLeR** [justinemter/pseudo-channel#64] opened 2017-12-01 18:48 UTC
Pseudo Channel won't work for Movies and TV Shows unless this is set in pseudo_config.py and the same library names are in PLEX.  I can't specify custom names:

plexLibraries = {
	"TV Shows"		: ["TV Shows"],
	"Movies"		: ["Movies"],
	"Commercials"	: ["Commercials"],
}

When I do specify custom names, like this...

plexLibraries = {
	"TV Shows"		: ["TV-Heroes"],
	"Movies"		: ["Mov-Musicals"],
	"Commercials"	: ["Commercials"],
}

...then the schedule will generate (although it won't display the HTML background if that video is not found), but the media play will result in an error, like this one:

Output showing library and media-play errors:
+++++ Queueing up 'The Rocky Horror Picture Show - A Preservation' to play right away.
##### Media Offset: '3248' seconds.
(4, 1510667465, 0, u'The Rocky Horror Picture Show - A Preservation', 0, 0, u'', 6236288, u'04:57:00 AM', u'1900-01-01 06:40:56.288000', u'everyday', u'Movies', u'/library/metadata/16261')
None
Invalid library section: Movies
##### There was an error trying to play the media.
+++++ Currently Playing: The Rocky Horror Picture Show - A Preservation
+++++ Html refresh flag: 1

It appears that the code is calling the section name rather than the user library name, for example:
movie =  self.PLEX.library.section(mediaType).get(mediaTitle)

MoRBiD

**Comment by justinemter** [comment] 2017-12-03 20:36
This seems to be now working on the "custom-section-name" branch. Making note of it here so we can close this when all's confirmed to be working.

**Closed** 2017-12-06 22:57 UTC
